version: '3.4'

services:
  # Fake SMTP server
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"


