# Generated by Django 5.0.3 on 2024-03-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fantasy", "Fantasy"),
                            ("horror", "Horror"),
                            ("science_fiction", "Science Fiction"),
                            ("action", "Action"),
                            ("comedy", "Comedy"),
                            ("romance", "Romance"),
                            ("adventure", "Adventure"),
                            ("thriller", "Thriller"),
                        ],
                        default="fantasy",
                        max_length=15,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.author"
                    ),
                ),
            ],
        ),
    ]
