# Generated by Django 5.0.4 on 2024-04-08 15:41

from django.db import migrations


def forwards_func(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Web Developer")


def backwards_func(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.delete(name="Web Developer")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
