# Generated by Django 5.0.4 on 2024-04-08 17:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20240408_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
