# Generated by Django 4.2.11 on 2024-03-05 19:09

import custom_auth_demos.accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="accountuser",
            managers=[
                ("objects", custom_auth_demos.accounts.models.AccountUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="accountuser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="accountuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
