# Generated by Django 4.2.11 on 2024-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("pages", models.IntegerField(default=0)),
                ("description", models.TextField(default="", max_length=100)),
                ("author", models.CharField(max_length=20)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Fantasy", "Fantasy"),
                            ("Science-Fiction", "Sciencefiction"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
